server:
  port: 8080

spring:
  application:
    name: ai-goal-planner

  datasource:
    url: jdbc:postgresql://localhost:5432/goalplanner
    username: postgres
    password: Shivang@14
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  sql:
    init:
      mode: never

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
          temperature: 0.7
          num-predict: 2048
      embedding:
        options:
          model: nomic-embed-text

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        initialize-schema: false

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration-ms: 86400000   # 24 hours

logging:
  level:
    com.aigoalplanner: DEBUG
    org.springframework.ai: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
